services:
  frontend:
    # image: ghcr.io/derrick-nuby/hello-server-vps:prod
    container_name: hello-server-vps
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3111:3000"
    environment:
      environment: "production"
    restart: unless-stopped
    networks:
      - hello-server-vps-app-network
networks:
  hello-server-vps-app-network:
